Разметка главной страницы
htmlacademy-adaptive/1751595-cat-energy-25 pull request #2
Opened 2022-04-06 08:21 UTC by Imaks6991

2022-04-06 17:33 UTC, andreysgra requested changes

2022-04-06 17:33 UTC, andreysgra commented on source/index.html
> +            </label>
Когда `input` находится внутри `label`, то связка по `for - id` не требуется. Но если у метки есть атрибут `for`, то у `input`, который с ней связан, должен быть `id` с таким же значением. Иначе ошибка валидации:
![image](https://user-images.githubusercontent.com/17790771/162031412-2d2cd942-e660-4756-a408-b12c8145c6c4.png)

Ну и мой совет: этот элемент стоит размечать `input type="range"` только в том случае, если сможете его стилизовать кроссбраузерно (список браузеров в [этом пункте](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-1-8) ТЗ). Также обратите внимание, что данный элемент в мобильной версии выглядит иначе, чем в планшетной. Поэтому проще сделать разметку с помощью `div` и `button`,

2022-04-06 17:33 UTC, andreysgra commented on source/index.html
> +        <a class="header__logo logo" href="#">
В `href` должна быть ссылка на главную страницу, а не якорь.

2022-04-06 17:33 UTC, andreysgra commented on source/index.html
> +        </a>
На мой взгляд вместо того, чтобы делить логотип-ссылку на два элемента с одной и той же функциональностью, лучше объединить в одно изображение. Ну или тогда просто поместить 2 изображения в одну ссылку. Две ссылки тут однозначно не нужны.

2022-04-06 17:33 UTC, andreysgra commented on source/index.html
> +        <button class="header__nav-button">
Тип кнопки не указан.

2022-04-06 17:33 UTC, andreysgra commented on source/index.html
> +          <li class="nav-item nav-item--current"><a class="nav-link" href="#">Главная</a></li>
Ссылка на главную страницу.

2022-04-06 17:33 UTC, andreysgra commented on source/index.html
> +          <li class="nav-item"><a class="nav-link" href="#">Подбор программмы</a></li>
Нужно поставить ссылки на соответствующие страницы сайта (такие, какими будут называться файлы внутренних страниц).

2022-04-06 17:33 UTC, andreysgra commented on source/index.html
> +            <img class="categories__image" width="36" height="50" src="img/categories-slim.svg" alt="Категория похудение (Slim)">
Эти иконки носят декоративный характер и добавлять их в разметку не нужно.
![image](https://user-images.githubusercontent.com/17790771/162033388-d5425783-5f65-4ee8-a9c5-239ee13efe43.png)

2022-04-06 17:33 UTC, andreysgra commented on source/index.html
> +        <a class="hero__link button" href="#">Подобрать программу</a>
[https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-4-2](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-4-2)

2022-04-06 17:33 UTC, andreysgra commented on source/index.html
> +            <img class="advantages__image" width="32" height="33" src="img/advantages-time.svg" alt="Функциональное питание">
Эти изображения тоже декоративные.
![image](https://user-images.githubusercontent.com/17790771/162033709-25230dec-29e8-491e-92cc-33927c63e433.png)

2022-04-06 17:33 UTC, andreysgra commented on source/index.html
> +              <span class="switcher__before">Было</span>
Эти элементы нужно разметить кнопками.
![image](https://user-images.githubusercontent.com/17790771/162033935-ebbe39f5-661c-46bf-88db-a62650d352cc.png)
То, что это кнопки можно понять по стайлгайду.

2022-04-06 17:33 UTC, andreysgra commented on source/index.html
> +        </div>
Есть такой [пункт ТЗ](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-3-8).

2022-04-07 13:17 UTC, Imaks6991 commented
1) ... input type="range" ... (блок с примером было-стало)
Надеюсь я правильно понял, как это сделать. В общем, теперь там 2 кнопки "было" и "стало" и блок-индикатор с кнопкой внутри

2) В href должна быть ссылка на главную страницу, а не якорь.
Добавил адреса во все ссылки

 3) На мой взгляд вместо того, чтобы делить логотип-ссылку на два элемента с одной и той же функциональностью, лучше объединить в одно изображение. Ну или тогда просто поместить 2 изображения в одну ссылку. Две ссылки тут однозначно не нужны.
Теперь оба изображения в одной ссылке

4) Тип кнопки не указан.
Во всех кнопках указал type="button"

5) Эти иконки носят декоративный характер и добавлять их в разметку не нужно. (блок с категориями slim и pro)
Сделаю их фоновым изображением

6) Эти изображения тоже декоративные. (блок advantages в разметке)
а их псевдоэлементом ::before у <li> в списке

7) Есть такой [пункт ТЗ](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-3-8).
Теперь лого и текст в одной ссылке

2022-04-07 18:12 UTC, andreysgra approved these changes

2022-04-07 18:12 UTC, andreysgra commented on source/index.html
> +          <li class="nav__item"><a class="nav__link" href="/form">Подбор программмы</a></li>
Здесь не совсем правильно. Нужно указывать расширение файла, на который ссылается ссылка. В данном случае это будет `.html`. Такие ссылки, как сделали вы, будут работать в некоторых CMS, где настроен редирект, но в нашем случае ссылки будут не валидными.

Правильный пример: `href="catalog.html"`

2022-04-07 18:12 UTC, andreysgra commented on source/index.html
> +        <a class="hero__link button" href="/form">Подобрать программу</a>
Здесь тоже нужно исправить ссылку на страницу формы. Чтобы понять, что работает не так, просто попробуйте перейти по своим ссылкам.

2022-04-07 18:12 UTC, merged