Разметка внутренних страниц
htmlacademy-adaptive/1751595-cat-energy-25 pull request #3
Opened 2022-04-08 14:27 UTC by Imaks6991

2022-04-08 18:46 UTC, andreysgra requested changes
Ну а по большому счёту всё хорошо.

2022-04-08 18:46 UTC, andreysgra commented on source/catalog.html
> +      <h1 class="title title--catalog container">Категории</h1>
```suggestion
      <h1 class="title title--catalog container">Каталог продукции</h1>
```

2022-04-08 18:46 UTC, andreysgra commented on source/catalog.html
> +          <img class="product__image" src="img/catalog-1.png" alt="Cat Energy PRO 500 г со вкусом курицы">
[Этот пункт](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-6-1) ТЗ описывает, что здесь нужна ссылка. (Изображение внутри ссылки).

2022-04-08 18:46 UTC, andreysgra commented on source/catalog.html
> +            <h3 class="product__title">Cat Energy PRO 500 г</h3>
[Этот пункт](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-6-1) ТЗ описывает, что здесь нужна ссылка. (Ссылка внутри заголовка. Если сделать наоборот, то кликабельной будет вся область заголовка, а не только текст).

2022-04-08 18:46 UTC, andreysgra commented on source/catalog.html
> +          <button class="product__button button" type="button">Заказать</button>
Это ссылка, так как в [этом пункте](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-6-2) ТЗ сказано, что нужен переход на другую страницу.

2022-04-08 18:46 UTC, andreysgra commented on source/catalog.html
> +          <a class="more__button button button--secondary" href="#">Показать все</a>
А вот здесь логичнее использовать кнопку, так как логика работы этого элемента реализуется с помощью JS.

2022-04-08 18:46 UTC, andreysgra commented on source/catalog.html
> +              <button class="additional__button button" type="button">Заказать</button>
Здесь лучше подходит ссылка, так как в случае неработоспособности JS будет осуществлён переход на страницу заказа.

2022-04-08 18:46 UTC, andreysgra commented on source/form.html
> +      <h1 class="title title--form container">Категории</h1>
```suggestion
      <h1 class="title title--form container">Подбор программы</h1>
```

2022-04-08 18:46 UTC, andreysgra commented on source/form.html
> +            <input class="form__general-text" type="text" name="name" id="name" placeholder="Барсик">
Здесь и далее: поля помеченные звёздочкой обязательны для заполнения, значит нужно добавить атрибут `required`.

2022-04-08 18:46 UTC, andreysgra commented on source/form.html
> +          <label class="form__label" for="name">
Если `<input>` находится внутри тега `<label>`, то связка по `for - id` не требуется. (Это просто к сведению, можно не исправлять).

2022-04-08 18:46 UTC, andreysgra commented on source/form.html
> +            <input class="form__radio-input" type="radio" name="program" id="slim" value="slim">
`checked`

2022-04-08 18:46 UTC, andreysgra commented on source/form.html
> +            <input class="form__checkbox-option" type="checkbox" name="sweetener" id="sweetener">
`checked` (чтобы хотя бы один был выбран).

2022-04-09 08:59 UTC, Imaks6991 commented
1) [Этот пункт](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-6-1) ТЗ описывает, что здесь нужна ссылка. (Изображение внутри ссылки).
[Этот пункт](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-6-1) ТЗ описывает, что здесь нужна ссылка. (Ссылка внутри заголовка. Если сделать наоборот, то кликабельной будет вся область заголовка, а не только текст).

ссылки добавил. Приемлемо ли, что это будут две ссылки, а не одна?

2) Это ссылка, так как в [этом пункте](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-6-2) ТЗ сказано, что нужен переход на другую страницу.

все кнопки "Заказать" у основных товаров теперь ссылки с якорем

3) Здесь лучше подходит ссылка, так как в случае неработоспособности JS будет осуществлён переход на страницу заказа. (блок с дополнительными товарами)

все кнопки "Заказать" у дополнительных товаров теперь тоже ссылки с якорем. Не нужно ли убирать атрибут href у тега ссылки, если планируется использовать js?

4) А вот здесь логичнее использовать кнопку, так как логика работы этого элемента реализуется с помощью JS. ("Показать все" в блоке more)

теперь это кнопка

5) Здесь и далее: поля помеченные звёздочкой обязательны для заполнения, значит нужно добавить атрибут required.

required у обязательных полей и checked у выбранных в макете опций поставил

2022-04-09 18:43 UTC, andreysgra approved these changes

2022-04-09 18:49 UTC, merged