3.8 Стилизация страниц
htmlacademy-adaptive/1751595-cat-energy-25 pull request #4
Opened 2022-04-16 11:28 UTC by Imaks6991

Мне кажется я перестарался, делая верстку не только для крупных блоков и, на мой взгляд, очень зря. В течение недели пока я это делал успел миллион раз запутаться в своем коде.

Я также собрал вопросы, на которые я не смог сам найти ответы:
1) у блока subtitle есть псеводэлемент after - линия, которая должна идти до конца страницы. Для этого я задал ей ширину 100vw, но это создает горизонтальный скрол от которого я не знаю, как избавиться.

2) в разметке товаров есть целых два divа, которые я добавил для того, чтобы правильно отобразить карточку товара, кнопку и разделяющую линию под товаром. Предполагаю, что весь блок product лучше вообще переделать под grid, чтобы избавиться от этих оберток?
Также div с одним лишь классом container есть в блоке example (главная страница), в футере и блоке more в каталоге. Считается ли правильной практикой так делать или лучше всегда это избегать?

3) у блока button при клике прозрачность текста становится 0.3, цвет самой кнопки не меняет прозрачности. Мне следует добавить span для текста внутри кнопки, чтобы это реализовать?

4) в стайлгайде толщина границы input в состоянии invalid и focus 2px, а в обычном и hover состоянии 1px. При значении border-box свойства box-sizing поле при нажатии все равно заметно меняет свой размер на странице и сдвигает все вокруг. Я оставил пока 1px в этих состояниях, т.к. не знаю как сделать это корректно

5) исходя из того, как я сделал разметку на главной странице, мне следует добавить фоновое изображение в мобильной версии для блока hero, а в десктоп для блока header?

6) Согласно критерию https://up.htmlacademy.ru/adaptive/25/criteries#b6 мне следует сделать grid сетку для всей страницы, я не заметил этот критерий сразу и не использовал grid. Тем не менее, если нет никакого сайдбара и блоки идут друг под другом, зачем его применять?

2022-04-16 19:10 UTC, andreysgra requested changes
Конечно, вы перестарались выполняя задние. Сетку сайта, даже крупных сеточных блоков, сейчас строить не нужно (тем более для всех страниц). Это усложняет работу над проектом вам и усложняет проверку задания мне. Поэтому я пока ограничился проверкой того, что описано в самом задании. В этом плане всё у вас достаточно корректно, а что нужно исправить, я написал в комментариях. Далее отвечу на ваши вопросы.

1. Если ширина блока задана с помощью `100vw`, то горизонтальная полоса прокрутки обязательно появится, так как в ширину окна браузера включается ширина вертикального скролла. Но это часть вашей проблемы. Суть несколько в ином. Для `::after` вы задали ширину `100vw`, то есть равную ширине видимой части окна браузера, но элемент позиционирован абсолютно и сдвинут относительно родительского элемента на значение равное ширине родителя (`left: 100%`), плюс значение `margin-left`. Получается, что левая координата `::after` привязана к точке, которая находится почти у правого края окна браузера, а значение его ширины равно ширине окна браузера. Элемент не помещается в сетку сайта, выходит за пределы родителя и появляется горизонтальная полоса прокрутки. В этом макете этот элемент интерфейса представляет определённую сложность и на данный момент мы его разбирать не будем, так как это не входит в рамки данного задания. Поэтому пока лучше его уберите до задания по лекции [Адаптивные декоративные элементы](https://up.htmlacademy.ru/adaptive/25/module/5).
2. Да, здесь вполне можно избавиться от лишней обёртки и сделать раскладку с помощью `grid`. А вот блок с классом `container` вполне можно и очень даже хорошо использовать, так как этот служебный класс помогает центрировать контент. Даже если нет иных свойств в этом блоке.
3. Ну это элементарно решается изменением свойства `color`. Просто цвет нужно записать не в HEX формате, а через функцию `rgba()`, в которой четвёртым параметром указывается непрозрачность (альфа-канал).
4. Правильнее будет делать обводку в данных состояниях через свойство `outline`, так как оно не изменяет геометрию элемента в отличии от свойства `border`. (Для **invalid** нужно будет использовать группу этих псевдо классов `:focus:invalid`).
5. Да, именно так. Правильно, что блок hero поместили в шапку сайта. Если размечать его в `main`, то без разных ухищрений и сложностей не обойтись при переходе на десктопную версию.
6. В рамках этого задания вообще не нужно касаться построения сетки, но в целом, критерий Б6 говорит лишь о том, что в проекте должны использоваться и гриды и флексы. А где их применять - на ваше усмотрение. Всё остальное - всего лишь рекомендация.

2022-04-16 19:10 UTC, andreysgra commented on source/sass/blocks/advantages.scss
> +    content: url("../../img/advantages-time.svg");
Ошибка в написании относительного пути в `url`. Такой путь вам наверное подставляет редактор кода, так как он основывается на пути нахождения файла изображения относительно соответствующего файла препроцессора. Но в результате компиляции будет создан файл CSS, относительно которого путь к файлу изображения будет выглядеть иначе: `url("../img/advantages-nutrition.svg")`. (Исправьте везде).

2022-04-16 19:10 UTC, andreysgra commented on source/sass/blocks/categories.scss
> +    background: $color-secondary url("../../img/categories-pro.svg") no-repeat 13px 24px;
Ошибка в относительном пути.

2022-04-16 19:10 UTC, andreysgra commented on source/sass/blocks/categories.scss
> +    background: url("../../img/arrow.svg") no-repeat;
Ошибка в относительном пути.

2022-04-16 19:10 UTC, andreysgra commented on source/sass/blocks/footer.scss
> +  &:hover > .footer__copyright-icon > path {
[Д10](https://up.htmlacademy.ru/adaptive/25/criteries#d10)

2022-04-16 19:10 UTC, andreysgra commented on source/sass/blocks/footer.scss
> +  &:active > .footer__copyright-icon > path {
[Д10](https://up.htmlacademy.ru/adaptive/25/criteries#d10)

2022-04-16 19:10 UTC, andreysgra commented on source/sass/blocks/header.scss
> +  background: url("../../img/mobile-button-open.svg") no-repeat center center;
Ошибка в относительном пути.

2022-04-16 19:10 UTC, andreysgra commented on source/sass/blocks/more.scss
> +    background: url("../../img/plus.svg") no-repeat;
Ошибка в относительном пути.

2022-04-16 19:10 UTC, andreysgra commented on source/sass/blocks/special.scss
> +  background: url("../../img/special.jpg") no-repeat center center;
Ошибка в относительном пути.

2022-04-16 19:10 UTC, andreysgra commented on source/sass/blocks/special.scss
> +    background-image: url("../../img/gift.svg");
Ошибка в относительном пути.

2022-04-16 19:10 UTC, andreysgra commented on source/sass/general.scss
> +}
У тега ` body` есть класс `page__body`, значит стили нужно описывать для класса, а не для тега (в файле **page.scss**).

2022-04-16 19:10 UTC, andreysgra commented on source/sass/general.scss
> +ul {
[Д16](https://up.htmlacademy.ru/adaptive/25/criteries#d16)

2022-04-16 19:10 UTC, andreysgra commented on source/sass/general.scss
> +p {
[Д16](https://up.htmlacademy.ru/adaptive/25/criteries#d16)

2022-04-16 19:10 UTC, andreysgra commented on source/sass/general.scss
> +}
`display: none` не скрывает доступно элемент, а просто удаляет его из HTML дерева, соответственно элемент будет недоступен для скринридера. Скрывать элементы нужно с помощью набора свойств `visually-hidden`.

2022-04-18 08:51 UTC, Imaks6991 commented
1) url везде поменял
2) селектор body поменял на .page__body и переместил в блок page.scss
3) вложенность больше двух уровней уменьшил
“&:active > .footer__copyright-icon > path”
теперь “&:hover .footer__copyright-path”
Это же два уровня вложенности? Первый - &:hover внутри блока родителя и второй - “ .footer…”
4) селекторы p и ul убрал. Считается ли плохой практикой использовать «обнуляющие» стили для глобальных селекторов? На мой взгляд очень удобно
5) .hidden теперь сделан по паттерну “visually-hidden” из интернета, в т.ч. из статьи «Как прятать» в htmlacademy
6) фоновое изображение для блока hero поставил
7) добавил color в .button при наведении, а opacity убрал
8) .form__general-text
заменил border на outline, а сам border теперь none

2022-04-18 19:15 UTC, andreysgra commented
> 3. вложенность больше двух уровней уменьшил
>    “&:active > .footer__copyright-icon > path”
>    теперь “&:hover .footer__copyright-path”
>    Это же два уровня вложенности? Первый - &:hover внутри блока родителя и второй - “ .footer…”

Да, всё верно.

> 4. селекторы p и ul убрал. Считается ли плохой практикой использовать «обнуляющие» стили для глобальных селекторов? На мой взгляд очень удобно

Не считается хорошим подходом. Особенно неудачно это будет выглядеть при работе в CMS.

> 5. .hidden теперь сделан по паттерну “visually-hidden” из интернета, в т.ч. из статьи «Как прятать» в htmlacademy

Теперь всё в порядке.

2022-04-18 19:29 UTC, andreysgra approved these changes
По текущему заданию всё хорошо, но так как вы ушли несколько дальше и уже построили сетку для мобильной версии, то прокомментирую некоторые моменты.

1. Фон в данном блоке
![image](https://user-images.githubusercontent.com/17790771/163863556-332c4081-de13-449a-8ad4-435c8a3064a7.png)
должен растягиваться на всю ширину окна браузера, также как в блоке с живым примером.
2. Мобильное меню по умолчанию должно быть открыто и находиться в потоке (описано в критерии [Б30](https://up.htmlacademy.ru/adaptive/25/criteries#b30)).
3. Для класса `.container`, который отвечает за центрирование контента нужно либо указать ширину через свойство `width`, если сетка будет с фиксированной шириной контента, либо задать минимальную ширину (это ширина контента в мобильной версии) и максимальную ширину (ширина контента десктопной версии). Также нужно задать паддинги по краям. Ширину `padding-left` и `padding-right` узнаём вычитая из общей ширины фрейма ширину контентной области и делим на 2. На примере мобильной версии: ширина контентной области ограниченная направляющими линиями равна 280px, а ширина всего фрейма - 320px. Значит ширина горизонтального паддинга равна (320 - 280) / 2 = 20.

2022-04-18 19:29 UTC, merged